
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const FONTS = [
    'Roboto', 'Open Sans', 'Lato', 'Montserrat', 'Oswald', 'Source Sans Pro', 'Slabo 27px', 'Raleway', 'PT Sans', 'Merriweather',
    'Roboto Condensed', 'Poppins', 'Noto Sans', 'Open Sans Condensed', 'Playfair Display', 'Ubuntu', 'Roboto Mono', 'Mukta', 'Muli', 'PT Serif',
    'Titillium Web', 'Nunito', 'Inconsolata', 'Noto Sans JP', 'PT Sans Narrow', 'Arimo', 'Work Sans', 'Noto Serif', 'Fira Sans', 'Quicksand',
    'Barlow', 'Nanum Gothic', 'Dosis', 'Cabin', 'Oxygen', 'Hind', 'Crimson Text', 'Barlow Condensed', 'Josefin Sans', 'Libre Baskerville',
    'Anton', 'Bitter', 'Nunito Sans', 'Fjalla One', 'Indie Flower', 'Arvo', 'Karla', 'Prompt', 'Slabo 13px', 'Lobster',
    'Monda', 'Pacifico', 'Abel', 'Signika', 'Russo One', 'Dancing Script', 'Permanent Marker', 'Caveat', 'Shadows Into Light', 'Righteous',
    'Courgette', 'Sacramento', 'Cookie', 'Great Vibes', 'Alex Brush', 'Satisfy', 'Allura', 'Kaushan Script', 'Tangerine', 'Yellowtail',
    'Lobster Two', 'Rochester', 'Grand Hotel', 'Cinzel', 'Unna', 'Cardo', 'Old Standard TT', 'Goudy Bookletter 1911', 'EB Garamond', 'Volkhov',
    'Gentium Basic', 'Neuton', 'Kreon', 'Josefin Slab', 'Rokkitt', 'Bevan', 'Patua One', 'Sanchez', 'Alfa Slab One', 'Hammersmith One',
    'Questrial', 'Voltaire', 'Chivo', 'News Cycle', 'Istok Web', 'Archivo', 'Zilla Slab', 'Heebo', 'Manrope', 'Public Sans',
    'Urbanist', 'Inter', 'DM Sans', 'Rubik', 'Lora', 'Frank Ruhl Libre', 'Spectral', 'Cormorant Garamond', 'Eczar', 'Trirong',
    'Taviraj', 'Sarabun', 'Kanit', 'Prompt', 'Chakra Petch', 'Mitr', 'Athiti', 'Pridi', 'Maitree', 'Pattaya',
    'Sriracha', 'Krub', 'Fahkwang', 'KoHo', 'Kodchasan', 'Niramit', 'Charm', 'Charmonman', 'Chonburi', 'Itim',
    'Srisakdi', 'Thasadith', 'Bai Jamjuree', 'K2D', 'Mali', 'Saza', 'Space Mono', 'Varela Round', 'Bungee',
    'Bungee Shade', 'Bungee Inline', 'Bungee Hairline', 'Bungee Outline', 'Rubik Mono One', 'Coiny', 'Fugaz One', 'Suez One', 'Viga', 'Carter One',
    'Racing Sans One', 'Black Ops One', 'Aldrich', 'Orbitron', 'Audiowide', 'Syncopate', 'Michroma', 'Jura', 'Khand', 'Teko',
    'Rajdhani', 'Exo 2', 'Do Hyeon', 'Gaegu', 'Gamja Flower', 'Gothic A1', 'Gugi', 'Hi Melody', 'Jua', 'Kirang Haerang',
    'Nanum Brush Script', 'Nanum Gothic Coding', 'Nanum Myeongjo', 'Noto Sans KR', 'Noto Serif KR', 'Poor Story', 'Song Myung', 'Stylish', 'Sunflower', 'Yeon Sung',
    'ZCOOL KuaiLe', 'ZCOOL QingKe HuangYou', 'ZCOOL XiaoWei', 'Ma Shan Zheng', 'Zhi Mang Xing', 'Liu Jian Mao Cao', 'Long Cang', 'Noto Sans SC', 'Noto Serif SC', 'Noto Sans TC',
    'Noto Serif TC', 'Crimson Pro', 'Literata', 'Red Hat Display', 'Red Hat Text', 'Lexend Deca', 'Lexend Giga', 'Lexend Mega', 'Lexend Peta', 'Lexend Tera',
    'Lexend Zetta', 'Lexend Exa', 'Alata', 'Calistoga', 'Vibes', 'Bebas Neue', 'Gotu', 'Gupter', 'Oxanium', 'Sora',
    'Epilogue', 'Syne', 'Kumbh Sans', 'Goldman', 'Rowdies', 'Piazzolla', 'Newsreader', 'Commissioner', 'Fraunces', 'Castoro',
    'Hachi Maru Pop', 'Reggae One', 'RocknRoll One', 'Stick', 'Train One', 'Yusei Magic', 'DotGothic16', 'Kiwi Maru', 'Otomanopee One', 'New Tegomin',
    'Potta One', 'Shippori Mincho', 'Shippori Mincho B1', 'Dela Gothic One', 'Yomogi', 'Hina Mincho', 'Kaisei Decol', 'Kaisei HarunoUmi', 'Kaisei Opti', 'Kaisei Tokumin',
    'Klee One', 'Rampart One', 'Zen Antique', 'Zen Antique Soft', 'Zen Kaku Gothic Antique', 'Zen Kaku Gothic New', 'Zen Kurenaido', 'Zen Loop', 'Zen Maru Gothic', 'Zen Old Mincho',
    'Zen Tokyo Zoo', 'Bonbon', 'Butterfly Kids', 'Caesar Dressing', 'Dr Sugiyama', 'Eater', 'Emilys Candy', 'Ewert', 'Fascinate', 'Fascinate Inline',
    'Faster One', 'Frijole', 'Geostar', 'Geostar Fill', 'Glass Antiqua', 'Hanalei', 'Hanalei Fill', 'Jolly Lodger', 'Keania One', 'Kumar One',
    'Kumar One Outline', 'Londrina Outline', 'Londrina Shadow', 'Londrina Sketch', 'Londrina Solid', 'Metal Mania', 'Monofett', 'Moul', 'Moulpali', 'Mrs Sheppards',
    'Nosifer', 'Original Surfer', 'Piedra', 'Plaster', 'Princess Sofia', 'Redressed', 'Ribeye', 'Ribeye Marrow', 'Risque', 'Rye',
    'Sail', 'Sancreek', 'Sarina', 'Sevillana', 'Shojumaru', 'Sirin Stencil', 'Snowburst One', 'Spicy Rice', 'Stalemate', 'Stalinist One',
    'Supermercado One', 'Trade Winds', 'Trykker', 'Underdog', 'UnifrakturCook', 'UnifrakturMaguntia', 'Unlock', 'Vast Shadow', 'Warnes', 'Wellfleet',
    'Wire One',
    'Abril Fatface', 'Acme', 'Advent Pro', 'Alice', 'Alike', 'Almendra', 'Amaranth', 'Amita', 'Andada Pro', 'Andika',
    'Angkor', 'Arapey', 'Architects Daughter', 'Archivo Black', 'Arizonia', 'Armata', 'Asap', 'Asar', 'Asset', 'Astloch',
    'Asul', 'Athelas', 'Atma', 'Average', 'Average Sans', 'Averia Gruesa Libre', 'Averia Libre', 'Averia Sans Libre', 'Averia Serif Libre', 'Azeret Mono',
    'Bad Script', 'Bahiana', 'Bahianita', 'Bakbak One', 'Balsamiq Sans', 'Balthazar', 'Bangers', 'Barlow Semi Condensed', 'Barriecito', 'Basiliko',
    'Baumans', 'Bayon', 'Belgrano', 'Bellefair', 'Belleza', 'Bellota', 'Bellota Text', 'BenchNine', 'Benne', 'Bentham',
    'Berkshire Swash', 'Besley', 'Big Shoulders Display', 'Big Shoulders Stencil Display', 'Big Shoulders Text', 'Bigelow Rules', 'Bigshot One', 'Bilbo', 'Bilbo Swash Caps', 'BioRhyme',
    'BioRhyme Expanded', 'Birthstone', 'Birthstone Bounce', 'Blaka', 'Blaka Hollow', 'Bodoni Moda', 'Bohar', 'Bokor', 'Bona Nova', 'Bonheur Royale',
    'Boogaloo', 'Bowlby One', 'Bowlby One SC', 'Brawler', 'Bubblegum Sans', 'Bubbler One', 'Buda', 'Buenard', 'Butcherman', 'Byzantine',
    'Cabin Condensed', 'Cabin Sketch', 'Calligraffitti', 'Cambo', 'Candal', 'Cantante', 'Cantarell', 'Cantata One', 'Cantora One', 'Capriola',
    'Caramel', 'Carrois Gothic', 'Carrois Gothic SC', 'Carvalho', 'Catamaran', 'Caudex', 'Cedarville Cursive', 'Celtics', 'Ceviche One', 'Chaco',
    'Changa', 'Changa One', 'Chanthaburi', 'Charis SIL', 'Chathura', 'Chau Philomene One', 'Chela One', 'Chelsea Market', 'Chenla', 'Cherish',
    'Cherry Cream Soda', 'Cherry Swash', 'Chewy', 'Chicle', 'Chilanka', 'Chokokutai', 'Chonburi', 'Cinzel Decorative', 'Clicker Script', 'Coda',
    'Codystar', 'Coiny', 'Combo', 'Comforter', 'Comforter Brush', 'Comic Neue', 'Coming Soon', 'Complex', 'Concert One', 'Condiment',
    'Content', 'Contrail One', 'Convergence', 'Copse', 'Corben', 'Corinthia', 'Cornerstone', 'Cousine', 'Coustard', 'Creepster',
    'Crete Round', 'Croissant One', 'Crushed', 'Cuprum', 'Cutive', 'Cutive Mono', 'Damion', 'Danfo', 'Dangrek', 'Darker Grotesque',
    'David Libre', 'Dawning of a New Day', 'Days One', 'Dekko', 'Delius', 'Delius Swash Caps', 'Delius Unicase', 'Della Respira', 'Denk One', 'Devonshire',
    'Dhurjati', 'Didact Gothic', 'Diplomata', 'Diplomata SC', 'Ditto', 'Donegal One', 'Doppio One', 'Dorsa', 'Duru Sans', 'Dynalight',
    'Eagle Lake', 'Easy Export', 'Ebenezer', 'Economica', 'Edge', 'Einstein', 'El Messiri', 'Electrolize', 'Elsie', 'Elsie Swash Caps',
    'Engagement', 'Englebert', 'Enriqueta', 'Ephesis', 'Ercot', 'Esteban', 'Euphoria Script', 'Expletus Sans', 'Explosion', 'Exponant',
    'Fanwood Text', 'Farro', 'Fashion', 'Fasthand', 'Fauna One', 'Faustina', 'Federant', 'Federo', 'Felipa', 'Fenix',
    'Finger Paint', 'Fixed', 'Flamenco', 'Flavors', 'Fondamento', 'Fontdiner Swanky', 'Forum', 'Francois One', 'Frank Ruhl Libre', 'Freckle Face',
    'Fredericka the Great', 'Fredoka One', 'Freehand', 'Fresca', 'Frijole', 'Fruktur', 'Futura', 'Gafatha', 'Gala', 'Galada',
    'Galdeano', 'Galindo', 'Gayathri', 'Georama', 'Geo', 'Gudea', 'Gueuzav', 'Gulzar', 'Gungsuh', 'Gurajada',
    'Habibi', 'Halant', 'Handlee', 'Hanken Grotesk', 'Hanuman', 'Happy Monkey', 'Harma', 'Harnon', 'Hasklig', 'Hauser',
    'Heidelberg', 'Hermeneutic', 'Heritage', 'Hexagon', 'Historian', 'Hollow', 'Holtwood One SC', 'Homemade Apple', 'Homenaje', 'Host',
    'Huninn', 'Iceberg', 'Iceland', 'Imbue', 'Imprima', 'Inder', 'Ink Draft', 'Inria Sans', 'Inria Serif', 'Inter Tight',
    'Ipsum', 'Island Moments', 'Isonomie', 'Jacquard 12', 'Jacquarda Bastarda 9', 'Jaini', 'Jaini Purva', 'Jaldi', 'JetBrains Mono', 'Jim Nightshade',
    'Joan', 'Jockey One', 'Jomhuria', 'Jomo', 'Josefin Sans', 'Jost', 'Joti One', 'Joyful', 'Judson', 'Julee',
    'Julius Sans One', 'Junge', 'Jura', 'Just Another Hand', 'Just Me Again Down Here', 'Kablammo', 'Kadwa', 'Kaffeesatz', 'Kalam', 'Kameron',
    'Kantumruy', 'Kantumruy Pro', 'Kasten', 'Kawkab Mono', 'Kdam Thmor', 'Keania One', 'Kelly Slab', 'Kenia', 'Kesterel', 'Kfaria',
    'Khula', 'Kiac', 'Kings', 'Kirsti', 'Kite One', 'Kivior', 'Kiwi Maru', 'Klee One', 'Knewave', 'Koala',
    'Konkhmer Sleokchher', 'Kosugi', 'Kosugi Maru', 'Kotta One', 'Koulen', 'Kranky', 'Krayat', 'Kreon', 'Kristi', 'Krona One',
    'Kronos', 'Kroun', 'KS Sans', 'Kufam', 'Kulim Park', 'KyivType Sans', 'Laila', 'Lakki Reddy', 'Lalezar', 'Lancelot',
    'Langar', 'Lateef', 'League Gothic', 'League Script', 'League Spartan', 'Leckerli One', 'Ledger', 'Lekton', 'Lemon', 'Lemonada',
    'Lexend', 'Lexend Deca', 'Libre Barcode 128', 'Libre Barcode 39', 'Libre Caslon Display', 'Libre Caslon Text', 'Libre Franklin', 'Life Savers', 'Lilita One', 'Lily Script One',
    'Limelight', 'Linden Hill', 'Line', 'Livvic', 'Lobster', 'Lohit Devanagari', 'Lohit Tamil', 'Lohit Telugu', 'Lola', 'Lora',
    'Love Ya Like A Sister', 'Loved by the King', 'Lovers Quarrel', 'Luckiest Guy', 'Lusitana', 'Lustria', 'Luxurious Roman', 'Luxurious Script', 'M Plus 1', 'M Plus 1p',
    'M Plus 2', 'M Plus Code Latin', 'M Plus Rounded 1c', 'Ma Shan Zheng', 'Macondo', 'Macondo Swash Caps', 'Mada', 'Madi', 'Magra', 'Maiden Orange',
    'Maitree', 'Major Mono Display', 'Mako', 'Mali', 'Mallanna', 'Mandali', 'Manjari', 'Manrope', 'Mansalva', 'Manuale',
    'Marcellus', 'Marcellus SC', 'Marck Script', 'Margarine', 'Marker Felt', 'Marko One', 'Marmelad', 'Martel', 'Martel Sans', 'Maru',
    'Maru Gothic', 'Marut', 'Marvel', 'Mate', 'Mate SC', 'Maven Pro', 'McLaren', 'Mea Culpa', 'Meddon', 'MedievalSharp',
    'Medula One', 'Meera Inimai', 'Megrim', 'Meie Script', 'Meow Script', 'Merienda', 'Merienda One', 'Merriweather Sans', 'Metal', 'Metal Mania',
    'Metamorphous', 'Metropolis', 'Metrophobic', 'Michroma', 'Milonga', 'Miltonian', 'Miltonian Tata', 'Mind', 'Ming', 'Miniver',
    'Miriam Libre', 'Mirza', 'Miss Fajardose', 'Mizra', 'Modak', 'Modern Antiqua', 'Mogra', 'Molengo', 'Molle', 'Monda',
    'Monofett', 'Monoton', 'Monsieur La Doulaise', 'Montaga', 'Montez', 'Montserrat Alternates', 'Montserrat Subrayada', 'Moo Lah Lah', 'Moon Dance', 'Moul',
    'Moulpali', 'Mountains of Christmas', 'Mouse Memoirs', 'Mr Bedfort', 'Mr Dafoe', 'Mr De Haviland', 'Mr Giotto', 'Mr Quest', 'Mr Sheffield', 'Mrs Saint Delafield',
    'Ms Madi', 'Mukta Mahee', 'Mukta Malar', 'Mukta Vaani', 'Murecho', 'Museo', 'Museo Sans', 'Museo Serif', 'Mystery Quest', 'NTR',
    'Nabla', 'Namdhinggo', 'Nanum Myeongjo', 'Nanum Pen Script', 'Neucha', 'Neuton', 'New Rocker', 'Niagara', 'Niconne', 'Niglo',
    'Nimbus', 'Nixie One', 'Nobile', 'Nofont', 'Nokora', 'Norican', 'Nosifer', 'Notable', 'Nothing You Could Do', 'Noticia Text',
    'Noto Color Emoji', 'Nova Cut', 'Nova Flat', 'Nova Mono', 'Nova Oval', 'Nova Round', 'Nova Script', 'Nova Slim', 'Nova Square', 'Numans',
    'Nunito', 'Odibee Sans', 'Odor Mean Chey', 'Offside', 'Oi', 'Old Standard TT', 'Oldenburg', 'Ole', 'Oleo Script', 'Oleo Script Swash Caps',
    'Open Sans', 'Oranienbaum', 'Orbitron', 'Oregano', 'Orelees One', 'Oriental', 'Original Surfer', 'Oswald', 'Outfit', 'Over the Rainbow',
    'Overlock', 'Overlock SC', 'Overpass', 'Overpass Mono', 'Ovo', 'Oxanium', 'Oxygen Mono', 'PT Mono', 'PT Sans Mono', 'PT Serif Caption',
    'Pacifico', 'Padauk', 'Padyakke Expanded One', 'Palanquin', 'Palanquin Dark', 'Pangolin', 'Paprika', 'Parisienne', 'Passero One', 'Passion One',
    'Passions Conflict', 'Pathway Gothic One', 'Patrick Hand', 'Patrick Hand SC', 'Patta', 'Pattaya', 'Patua One', 'Pavanam', 'Paytone One', 'Peddana',
    'Peralta', 'Petit Formal Script', 'Petrona', 'Philosopher', 'Phudu', 'Piazzolla', 'Picnic', 'Pie', 'Piedra', 'Pinyon Script',
    'Pirata One', 'Plaster', 'Play', 'Playball', 'Playfair Display SC', 'Playpen Sans', 'Playlist', 'Playtime', 'Plus Jakarta Sans', 'Podkova',
    'Poiret One', 'Poller One', 'Poly', 'Pompiere', 'Pontano Sans', 'Poor Story', 'Pora', 'Port Lligat Sans', 'Port Lligat Slab', 'Post No Bills Colombo',
    'Potto One', 'Prata', 'Preahvihear', 'Press Start 2P', 'Pridi', 'Prince', 'Princess Sofia', 'Prociono', 'Prompt', 'Prosto One',
    'Proza Libre', 'Public Sans', 'Puppert', 'Puritan', 'Purple Purse', 'Quando', 'Quantico', 'Quattrocento', 'Quattrocento Sans', 'Questrial',
    'Quicksand', 'Quintessential', 'Qwigley', 'Qwitcher Grypen', 'Racing Sans One', 'Radley', 'Rajdhani', 'Rakkas', 'Raleway Dots', 'Ramabhadra',
    'Ramaraja', 'Rambla', 'Ramneek', 'Ranchers', 'Rancho', 'Ranga', 'Rasa', 'Rationale', 'Ravi Prakash', 'Readex Pro',
    'Recursive', 'Red Hat Display', 'Red Hat Mono', 'Redressed', 'Reem Kufi', 'Reem Kufi Fun', 'Reem Kufi Ink', 'Reenie Beanie', 'Revalia', 'Rhodium Libre',
    'Ribeye', 'Ribeye Marrow', 'Rice', 'Richola', 'Righteous', 'Rigid', 'Risque', 'Road Rage', 'Robert', 'Roboto Flex',
    'Roboto Serif', 'Rochester', 'Rock Salt', 'RocknRoll One', 'Rokkitt', 'Romanesco', 'Ropa Sans', 'Rosario', 'Rosarivo', 'Rouge Script',
    'Rowdies', 'Rozha One', 'Rubik Beastly', 'Rubik Bubbles', 'Rubik Burned', 'Rubik Distressed', 'Rubik Glitch', 'Rubik Microbe', 'Rubik Mono One', 'Rubik Puddles',
    'Rubik Wet Paint', 'Ruda', 'Rufina', 'Ruge Boogie', 'Ruluko', 'Rum Raisin', 'Ruslan Display', 'Russo One', 'Ruthie', 'Rye',
    'STIX Two Text', 'Sahitya', 'Sail', 'Saira', 'Saira Condensed', 'Saira Extra Condensed', 'Saira Semi Condensed', 'Saira Stencil One', 'Sajak', 'Salsa',
    'Sanchez', 'Sancreek', 'Sansita', 'Sansita Swashed', 'Sarabun', 'Sarala', 'Sarina', 'Sarpanch', 'Sassy Frass', 'Satisfy',
    'Saurashtra', 'Savant', 'Savate', 'Sawal', 'Scada', 'Scheherazade New', 'Schoolbell', 'Scope One', 'Seaweed Script', 'Secular One',
    'Sedgwick Ave', 'Sedgwick Ave Display', 'Sen', 'Send Flowers', 'Sevillana', 'Seymour One', 'Shadows Into Light', 'Shadows Into Light Two', 'Shalimar', 'Shantell Sans',
    'Shanti', 'Share', 'Share Tech', 'Share Tech Mono', 'Shippori Antique', 'Shippori Antique B1', 'Shojumaru', 'Short Stack', 'Shizuru', 'Shree Devanagari 714',
    'Siemreap', 'Sigmar', 'Sigmar One', 'Signika', 'Signika Negative', 'Simonetta', 'Sintony', 'Sirin Stencil', 'Six Caps', 'Skranji',
    'Slabo 13px', 'Slabo 27px', 'Slackey', 'Smokum', 'Smooch', 'Smooch Sans', 'Smythe', 'Sniglet', 'Snippet', 'Snowburst One',
    'Sofadi One', 'Sofia', 'Sofia Sans', 'Sofia Sans Condensed', 'Sofia Sans Extra Condensed', 'Sofia Sans Semi Condensed', 'Solitreo', 'Solway', 'Song Myung', 'Sora',
    'Sorts Mill Goudy', 'Source Code Pro', 'Source Serif Pro', 'Space Grotesk', 'Space Mono', 'Special Elite', 'Spectral', 'Spicy Rice', 'Spinnaker', 'Spirax',
    'Splash', 'Spline Sans', 'Spline Sans Mono', 'Squada One', 'Sree Krushnadevaraya', 'Sriracha', 'Srisakdi', 'Staatliches', 'Stalemate', 'Stalinist One',
    'Stardos Stencil', 'Stark', 'Stay', 'Stellar', 'Step', 'Stint Ultra Condensed', 'Stint Ultra Expanded', 'Stoke', 'Strait', 'Style Script',
    'Stylest', 'Stylish', 'Sue Ellen Francisco', 'Suez One', 'Sulphur Point', 'Sumana', 'Sunflower', 'Sunshiney', 'Supermercado One', 'Sura',
    'Suranna', 'Suravaram', 'Suwannaphum', 'Swanky and Moo Moo', 'Syncopate', 'Syne', 'System', 'Tabb', 'Tac One', 'Tager',
    'Tagu', 'Tagus', 'Tahlequah', 'Tako', 'Talic', 'Tall', 'Tally', 'Tamarillo', 'Tangerine', 'Taprom',
    'Tar', 'Tark', 'Tasa', 'Tatum', 'Taur', 'Tavar', 'Tave', 'Taxis', 'Tebas', 'Techo',
    'Teko', 'Telex', 'Tenali Ramakrishna', 'Tenor Sans', 'Text Me One', 'Texturina', 'Thabit', 'Thasadith', 'The Girl Next Door', 'The Junction',
    'The Nautigal', 'The Quest', 'The Story', 'Theatre', 'Thetis', 'Thonburi', 'Three', 'Thura', 'Ti', 'Tian',
    'Tick', 'Tico', 'Tiger', 'Tiki', 'Tikki', 'Tiko', 'Tila', 'Tile', 'Tilia', 'Tilo',
    'Tilt Neon', 'Tilt Prism', 'Tilt Warp', 'Tim', 'Tina', 'Tini', 'Tino', 'Tint', 'Tip', 'Tir',
    'Tiresias', 'Tiri', 'Tiro Bangla', 'Tiro Devanagari Hindi', 'Tiro Devanagari Marathi', 'Tiro Devanagari Sanskrit', 'Tiro Gurmukhi', 'Tiro Kannada', 'Tiro Tamil', 'Tiro Telugu',
    'Tish', 'Titillium Web', 'Tito', 'Titus', 'Tix', 'Tiz', 'Tobby', 'Tobias', 'Toby', 'Toco',
    'Todd', 'Todo', 'Toff', 'Toga', 'Togi', 'Togo', 'Tok', 'Toko', 'Toku', 'Tola',
    'Toli', 'Tolo', 'Tom', 'Toma', 'Tomb', 'Tomi', 'Tommy', 'Tomo', 'Toms', 'Tony',
    'Top', 'Tops', 'Tor', 'Tora', 'Tore', 'Toros', 'Torp', 'Tors', 'Tory', 'Tosa',
    'Tosi', 'Toso', 'Toss', 'Tot', 'Tote', 'Toto', 'Tots', 'Tout', 'Tove', 'Town',
    'Tox', 'Toy', 'Toz', 'Trace', 'Trad', 'Trade Winds', 'Trail', 'Train One', 'Trans', 'Traut',
    'Tree', 'Trirong', 'Trix', 'Triz', 'Trob', 'Trog', 'Trom', 'Tron', 'Trop', 'Tros',
    'Trot', 'Trou', 'Trox', 'Troy', 'Troz', 'Trub', 'Truculenta', 'True', 'Trykker', 'Tsad',
    'Tsai', 'Tsar', 'Tsay', 'Tse', 'Tsi', 'Tso', 'Tsu', 'Tsv', 'Tsy', 'Tu',
    'Tub', 'Tuck', 'Tue', 'Tuf', 'Tug', 'Tuh', 'Tuk', 'Tul', 'Tum', 'Tun',
    'Tung', 'Tuo', 'Tup', 'Tur', 'Tus', 'Tut', 'Tux', 'Tuy', 'Tuz', 'Tva',
    'Tve', 'Tvi', 'Tvo', 'Tvu', 'Tvy', 'Tw', 'Twi', 'Two', 'Twy', 'Ty',
    'Tye', 'Tyf', 'Tyg', 'Tyh', 'Tyi', 'Tyk', 'Tyl', 'Tym', 'Tyn', 'Typ',
    'Tyq', 'Tyr', 'Tys', 'Tyt', 'Tyu', 'Tyv', 'Tyw', 'Tyx', 'Tyy', 'Tyz'
];

async function main() {
    console.log("Seeding GoogleFont library...");

    try {
        const data = FONTS.map(name => ({ name }));

        await prisma.googleFont.createMany({
            data,
            skipDuplicates: true,
        });

        console.log(`Successfully seeded ${FONTS.length} fonts.`);
    } catch (e) {
        console.error("Error seeding fonts:", e);
    } finally {
        await prisma.$disconnect();
    }
}

main();
