export const POPULAR_GOOGLE_FONTS = [
    'Roboto',
    'Open Sans',
    'Lato',
    'Montserrat',
    'Oswald',
    'Source Sans Pro',
    'Slabo 27px',
    'Raleway',
    'PT Sans',
    'Merriweather',
    'Roboto Condensed',
    'Poppins',
    'Noto Sans',
    'Open Sans Condensed',
    'Playfair Display',
    'Ubuntu',
    'Roboto Mono',
    'Mukta',
    'Muli',
    'PT Serif',
    'Titillium Web',
    'Nunito',
    'Inconsolata',
    'Noto Sans JP',
    'PT Sans Narrow',
    'Arimo',
    'Work Sans',
    'Noto Serif',
    'Fira Sans',
    'Quicksand',
    'Barlow',
    'Nanum Gothic',
    'Dosis',
    'Cabin',
    'Oxygen',
    'Hind',
    'Crimson Text',
    'Barlow Condensed',
    'Josefin Sans',
    'Libre Baskerville',
    'Anton',
    'Bitter',
    'Nunito Sans',
    'Fjalla One',
    'Indie Flower',
    'Arvo',
    'Karla',
    'Prompt',
    'Slabo 13px',
    'Lobster',
    'Monda',
    'Pacifico',
    'Abel',
    'Signika',
    'Russo One',
    'Dancing Script',
    'Permanent Marker',
    'Caveat',
    'Shadows Into Light',
    'Righteous',
    'Courgette',
    'Sacramento',
    'Cookie',
    'Great Vibes',
    'Alex Brush',
    'Satisfy',
    'Allura',
    'Kaushan Script',
    'Tangerine',
    'Yellowtail',
    'Lobster Two',
    'Rochester',
    'Grand Hotel',
    'Cinzel',
    'Unna',
    'Cardo',
    'Old Standard TT',
    'Goudy Bookletter 1911',
    'EB Garamond',
    'Volkhov',
    'Gentium Basic',
    'Neuton',
    'Kreon',
    'Josefin Slab',
    'Rokkitt',
    'Bevan',
    'Patua One',
    'Sanchez',
    'Alfa Slab One',
    'Hammersmith One',
    'Questrial',
    'Voltaire',
    'Chivo',
    'News Cycle',
    'Istok Web',
    'Archivo',
    'Zilla Slab',
    'Heebo',
    'Manrope',
    'Public Sans',
    'Urbanist',
    'Inter',
    'DM Sans',
    'Rubik',
    'Lora',
    'Frank Ruhl Libre',
    'Spectral',
    'Cormorant Garamond',
    'Eczar',
    'Trirong',
    'Taviraj',
    'Sarabun',
    'Kanit',
    'Prompt',
    'Chakra Petch',
    'Mitr',
    'Athiti',
    'Pridi',
    'Maitree',
    'Pattaya',
    'Sriracha',
    'Krub',
    'Fahkwang',
    'KoHo',
    'Kodchasan',
    'Niramit',
    'Charm',
    'Charmonman',
    'Chonburi',
    'Itim',
    'Srisakdi',
    'Thasadith',
    'Bai Jamjuree',
    'K2D',
    'Mali',
    'Niramit',
    'Saza',
    'Space Mono',
    'Varela Round',
    'Bungee',
    'Bungee Shade',
    'Bungee Inline',
    'Bungee Hairline',
    'Bungee Outline',
    'Rubik Mono One',
    'Coiny',
    'Fugaz One',
    'Suez One',
    'Viga',
    'Carter One',
    'Racing Sans One',
    'Black Ops One',
    'Aldrich',
    'Orbitron',
    'Audiowide',
    'Syncopate',
    'Michroma',
    'Jura',
    'Khand',
    'Teko',
    'Rajdhani',
    'Exo 2',
    'Do Hyeon',
    'Gaegu',
    'Gamja Flower',
    'Gothic A1',
    'Gugi',
    'Hi Melody',
    'Jua',
    'Kirang Haerang',
    'Nanum Brush Script',
    'Nanum Gothic Coding',
    'Nanum Myeongjo',
    'Noto Sans KR',
    'Noto Serif KR',
    'Poor Story',
    'Song Myung',
    'Stylish',
    'Sunflower',
    'Yeon Sung',
    'ZCOOL KuaiLe',
    'ZCOOL QingKe HuangYou',
    'ZCOOL XiaoWei',
    'Ma Shan Zheng',
    'Zhi Mang Xing',
    'Liu Jian Mao Cao',
    'Long Cang',
    'Noto Sans SC',
    'Noto Serif SC',
    'Noto Sans TC',
    'Noto Serif TC',
    'Crimson Pro',
    'Literata',
    'Red Hat Display',
    'Red Hat Text',
    'Lexend Deca',
    'Lexend Giga',
    'Lexend Mega',
    'Lexend Peta',
    'Lexend Tera',
    'Lexend Zetta',
    'Lexend Exa',
    'Alata',
    'Calistoga',
    'Vibes',
    'Bebas Neue',
    'Gotu',
    'Gupter',
    'Oxanium',
    'Sora',
    'Epilogue',
    'Syne',
    'Kumbh Sans',
    'Goldman',
    'Rowdies',
    'Piazzolla',
    'Newsreader',
    'Commissioner',
    'Fraunces',
    'Castoro',
    'Hachi Maru Pop',
    'Reggae One',
    'RocknRoll One',
    'Stick',
    'Train One',
    'Yusei Magic',
    'DotGothic16',
    'Kiwi Maru',
    'Otomanopee One',
    'New Tegomin',
    'Potta One',
    'Shippori Mincho',
    'Shippori Mincho B1',
    'Dela Gothic One',
    'Yomogi',
    'Hina Mincho',
    'Kaisei Decol',
    'Kaisei HarunoUmi',
    'Kaisei Opti',
    'Kaisei Tokumin',
    'Klee One',
    'Rampart One',
    'Zen Antique',
    'Zen Antique Soft',
    'Zen Kaku Gothic Antique',
    'Zen Kaku Gothic New',
    'Zen Kurenaido',
    'Zen Loop',
    'Zen Maru Gothic',
    'Zen Old Mincho',
    'Zen Tokyo Zoo',
    'Bonbon',
    'Butterfly Kids',
    'Caesar Dressing',
    'Dr Sugiyama',
    'Eater',
    'Emilys Candy',
    'Ewert',
    'Fascinate',
    'Fascinate Inline',
    'Faster One',
    'Frijole',
    'Geostar',
    'Geostar Fill',
    'Glass Antiqua',
    'Hanalei',
    'Hanalei Fill',
    'Jolly Lodger',
    'Keania One',
    'Kumar One',
    'Kumar One Outline',
    'Londrina Outline',
    'Londrina Shadow',
    'Londrina Sketch',
    'Londrina Solid',
    'Metal Mania',
    'Monofett',
    'Moul',
    'Moulpali',
    'Mrs Sheppards',
    'Nosifer',
    'Original Surfer',
    'Piedra',
    'Plaster',
    'Princess Sofia',
    'Redressed',
    'Ribeye',
    'Ribeye Marrow',
    'Risque',
    'Rye',
    'Sail',
    'Sancreek',
    'Sarina',
    'Sevillana',
    'Shojumaru',
    'Sirin Stencil',
    'Snowburst One',
    'Spicy Rice',
    'Stalemate',
    'Stalinist One',
    'Supermercado One',
    'Trade Winds',
    'Trykker',
    'Underdog',
    'UnifrakturCook',
    'UnifrakturMaguntia',
    'Unlock',
    'Vast Shadow',
    'Warnes',
    'Wellfleet',
    'Wire One'
];
